### ISSUE TITLE
Java FFI Makefile does not work correctly on Mac OS

### ISSUE THREAD

**Issue by rheitjoh** [herumi/mcl#105]
## Problem
The Java FFI Makefile (under `/ffi/java/Makefile`) is missing an include path for `jni_md.h` for Mac OS. This file–on Mac OS–is stored under `$(JAVA_INC)/darwin` which is not added as a CFLAG. The compilation therefore fails due to not being able to find `jni_md.h`.

## How to fix
Depending on the OS, either `$(JAVA_INC)/linux` or `$(JAVA_INC)/darwin` should be added to the CFLAGS.

Example fix moving the addage of the include path into the OS condition:

```Makefile
ifeq ($(UNAME_S),Darwin)
  JAVA_INC?=-I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/JavaVM.framework/Headers/
  CFLAGS+=$(JAVA_INC)/darwin
else
  JAVA_INC?=-I/usr/lib/jvm/default-java/include
#JAVA_INC=-I/usr/lib/jvm/java-7-openjdk-amd64/include
  CFLAGS+=-z noexecstack $(JAVA_INC)/linux
  LDFLAGS+=-lrt
endif
CFLAGS+=$(JAVA_INC) -I $(TOP_DIR)/include -I $(TOP_DIR)/../xbyak -I $(TOP_DIR)/../cybozulib/include -Wno-strict-aliasing
```
I can create a pull request for this, but due to #104 the Java FFI is not working atm.

**Comment by herumi** [comment]
I tested `make test` at ffi/java on Intel macOS and it runs well.
What error is there?

```
% uname -a
Darwin macpro.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64

mcl/ffi/java% make test_mcl
mkdir -p com/herumi/mcl
...
OK : verify signature
all test passed
```
[a.log](https://github.com/herumi/mcl/files/6112609/a.log)

**Comment by rheitjoh** [comment]
I personally don't have a Mac, but the error was that `jni_md.h` cannot be found which makes sense cause that file is contained in `$(JAVA_INC)/darwin` (at least on my colleague's Macs). That path is missing in the Makefile.

Where is your `jni_md.h` and which Java version are you using? I wonder if they changed the location of `jni_md.h` for some Java version.

**Comment by feidens** [comment]
Hi from the Mac colleague,

I think the assumption that   ```I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/JavaVM.framework/Headers/``` exists is false. Usually it does not exists if you just install a jdk. 
(This looks more related to command line tools that Xcode installs, but also ```xcode-select --install```does not help, so 🤷 )

**Comment by herumi** [comment]
Thank you for the report. I can understand it.
I add `JAVA_INC_DIR` to Makefile.
It runs well for both openjdk 12 and 15.
Could you try https://github.com/herumi/mcl/commit/a06bfd3b8f39b967071e8758ca76ae31268ab81c#diff-dbd98d720cb11066d7e6b68a132cec80651f1099c09eefc3a03263f7cfc0bd39 ?

```
make test_mcl JAVA_INC_DIR=/Library/Java/JavaVirtualMachines/openjdk-12.0.1.jdk/Contents/Home/include/
make test_mcl JAVA_INC_DIR=/usr/local/opt/openjdk/include/
```



```
ls /usr/local/opt/openjdk@15/include/
./                      classfile_constants.h@  jawt_md.h@              jni.h@                  jvmti.h@
../                     jawt.h@                 jdwpTransport.h@        jni_md.h@               jvmticmlr.h@
```

```
ls /Library/Java/JavaVirtualMachines/openjdk-12.0.1.jdk/Contents/Home/include/
./                      classfile_constants.h   jawt.h                  jni.h                   jvmticmlr.h
../                     darwin/                 jdwpTransport.h         jvmti.h
```

**Comment by JanBobolz** [comment]
```
jan@Jans-MBP java % make test JAVA_INC=-I/Library/Java/JavaVirtualMachines/openjdk-14.0.1.jdk/Contents/Home/include
[...]
all test passed
```

Works for me now. Thanks!
