### ISSUE TITLE
How can i get generator "g1" of G1 and generator "g2" of G2 in Java? 

### ISSUE THREAD

**Issue by Henzi96** [herumi/mcl#111]
Hello, I am trying to implement Weak Boneh Boyah signature. There is a step, where generators "g1" and "g2"  form G1/G2 groups are needed. How can i get them in Java ? Thanks

**Comment by herumi** [comment]
`hashAndMapToG1` and `hashAndMapToG2` always generate a generator of G1 and G2.

**Comment by Henzi96** [comment]
Hm, ok. My friend told me: "Use this as a generator of G1":
1 .....regarding to: 1 <x> <y> ; affine coordinate
g1(X) : 2523648240000001BA344D80000000086121000000000013A700000000000012
g1(Y) : 0000000000000000000000000000000000000000000000000000000000000001

Is it correct ? I am working with BN254 curve in Java

**Comment by herumi** [comment]
```
G1 P = new G1();
P.setStr("1 2523648240000001BA344D80000000086121000000000013A700000000000012 0000000000000000000000000000000000000000000000000000000000000001", 16);
```

**Comment by Henzi96** [comment]
Exactly. Thanks
