### ISSUE TITLE
How can i map 65Bytes (130 hexa chars) as a point on curve ?

### ISSUE THREAD

**Issue by Henzi96** [herumi/mcl#112]
Lets say, that i recieved this data from the system, where the **C** implementation of MCL is running.
**1B** 04 
**32B** 09179D6EB4E81E8E368CBD67F508877D6DE4EFF2202F3A3535490A25FCD9A999
**32B** 14972EA5853D7546D6A6D7A77FF584997D74E42AFF98DFDBB28D07F97AC2736E

How can i map this data as a point on curve in Java ? I noticed, that after execusion of this: **G1 Q = new G1()**, there are some random data, which looks like: this
**1** **4c21e376a683687523e4635c2ac9a2a0f264908f6ad06bb9dd784bb73650ba9** 
   **b52dd5ac97d74bd7cdd9dd3f3431248c3f4579a2bc9ec996c3daaf152abe4c9**

**Comment by herumi** [comment]
>that i recieved this data from the system, where the C implementation of MCL is running.
>1B 04
>32B 09179D6EB4E81E8E368CBD67F508877D6DE4EFF2202F3A3535490A25FCD9A999
>32B 14972EA5853D7546D6A6D7A77FF584997D74E42AFF98DFDBB28D07F97AC2736E

What API did you use to get it?

The best way to move data among multi environments is to use `serialize()` and `deserialize()` method.

**Comment by Henzi96** [comment]
Hm.. i think that i solved this problem. **"04"** is redundant. Remaining hexadecimal characters are representation of the point on the curve. There are 128 chars ( 64 Bytes ) ---> X...32Bytes, Y.....32Bytes

**Comment by herumi** [comment]
>"04" is redundant. 

It shows Jacobi coordinate.
https://github.com/herumi/mcl/blob/master/api.md#get-string

**Comment by Henzi96** [comment]
Yes, but in this case, "04" means something else as the second developer says. Its because of MultOS compatibility.
