### ISSUE TITLE
How to find an inverse element for another element in Fr ?

### ISSUE THREAD

**Issue by Henzi96** [herumi/mcl#114]
Hello. I would like to get an inverse element to another element in Java? Is this a correct procedure ? Thanks
`Fr element = new Fr();`
`element.setByCSPRNG();`
`Fr inverse_element = new Fr();`
`com.herumi.mcl.Mcl.neg(inverse_element, element);`

**Comment by herumi** [comment]
I've added the method at https://github.com/herumi/mcl/commit/de148824a4fd7320e7cd42433a2b64ec6a991683 .
