### ISSUE TITLE
Support for iOS

### ISSUE THREAD

**Issue by Henzi96** [herumi/mcl#124]
Is there any way to run the MCL library on an Apple mobile device ? Or more generally on iOS devices. I noticed within the library description that support for iOS exists. Also, is there any makefiles that need to be created and the library compiled for the iOS processor architecture? Thank you for the answer.

**Comment by herumi** [comment]
Could you use a Makefile in https://github.com/herumi/bls-eth-go-binary#ios ?
The compiled binary `libbls384_256.a` contains all functions defined in `include/mcl/bn.h`.
