### ISSUE TITLE
she.hのrust用のbinding実装のお願い

### ISSUE THREAD

**Issue by daichihattori** [herumi/mcl#127]
現在mclをmcl-rustを用いて使わせていただいています。
mclのshe.hのrust bindingを使いたいのですがお時間があるときに実装していただいてもよろしいでしょうか？

**Comment by herumi** [comment]
どんな用途を考えていますか。可能なら教えてください。

**Comment by daichihattori** [comment]
返信ありがとうございます。
現在、私はpythonでPaillier暗号を用いて加法準同型の演算を作っていましたが、効率化の観点から、rustでの実装に切り替えようと考えています。さらにペリエ暗号をLifted-elgamalにすることでさらなる高速化が見込めるのではないかと考え、お願いしました。

**Comment by herumi** [comment]
承知しました。すぐには難しいですが検討します。

**Comment by daichihattori** [comment]
ありがとうございます。

**Comment by herumi** [comment]
とりあえず先にPython bindingに`initG1only(SECP256K1)`を追加しました。

https://github.com/herumi/mcl/blob/master/ffi/python/she.py#L296-L314

**Comment by herumi** [comment]
最低限必要なところは概ね実装しました。
https://github.com/herumi/she-rust

**Comment by daichihattori** [comment]
お忙しいところありがとうございました。

**Comment by daichihattori** [comment]
先ほど動作を確認しました。issueを閉じます。ありがとうございました。
