### ISSUE TITLE
Example code for operator overloading in C++

### ISSUE THREAD

**Issue by guruvamsi-policharla** [herumi/mcl#130]
Is there an example file for operator overloading in C++? Such as multiplication, group addition, etc. Currently, the examples don't use it and I had to dig through the code/previous issues to figure out how to use it. I'm happy to create one.

**Comment by herumi** [comment]
I'll make the document.
Could you see https://github.com/herumi/mcl/blob/master/test/fp_test.cpp and https://github.com/herumi/mcl/blob/master/test/ec_test.cpp#L67 for some examples?

**Comment by guruvamsi-policharla** [comment]
Thanks!
