### ISSUE TITLE
Multi-thread C api for mclBn_millerLoopVec

### ISSUE THREAD

**Issue by fateh321** [herumi/mcl#133]
I want to use the function mclBn_millerLoopVec() to implement cryptographic pairing. In order to speed up this processing for large vector sizes, I want to parallelize this function using multi-threading and distributing it over all cores. Is there a feature or flag for this in the API.
Thanks a lot.

**Comment by herumi** [comment]
I've added `millerLoopVecMT`.

https://github.com/herumi/mcl/blob/dev/sample/mt_test.cpp

Could you try it?
```
make bin/mt_test.exe MCL_USE_OMP=1
bin/mt_test.exe -n 1000 -cpu 3
```

**Comment by herumi** [comment]
C api is https://github.com/herumi/mcl/blob/dev/include/mcl/bn.h#L470-L472 .

**Comment by fateh321** [comment]
It works well. Thanks a ton!
