### ISSUE TITLE
error: no member named 'setStr' in '__gmp_expr<mpz_t, mpz_t>'                         z2_.setStr(&b, z2, 16); assert(b); (void)b;

### ISSUE THREAD

**Issue by abolfazlyounesi** [herumi/mcl#136]
getting the `error: no member named 'setStr' in '__gmp_expr<mpz_t, mpz_t>'
                        z2_.setStr(&b, z2, 16); assert(b); (void)b;`
while trying to use cmake for building

OS: mac os 12.0.1

**Comment by herumi** [comment]
Thank you for pointing that out. I forgot GMP.
I've fixed it at https://github.com/herumi/mcl/releases/tag/v1.56 .
