### ISSUE TITLE
Question about DST 

### ISSUE THREAD

**Issue by b00f** [herumi/mcl#138]
The DST that is defined here is not compatible with the spec. It's defined like this:
https://github.com/herumi/mcl/blob/41497c9cf9b38edb6d1aafbafaf2237848b0dee7/include/mcl/mapto_wb19.hpp#L556 

However Spec [definition](https://datatracker.ietf.org/doc/html/draft-irtf-cfrg-bls-signature-04#section-4.2.1) recommends different DST for different schemes. Is there any reason for this?

**Comment by aguycalled** [comment]
it would help to be able to set the DST label for other schemes

**Comment by herumi** [comment]
Okay, I'll add the api.

**Comment by herumi** [comment]
FYI. "BLS_SIG_BLS12381G1_XMD:SHA-256_SSWU_RO_POP_" is for Ethereum.
https://pypi.org/project/py-ecc/

**Comment by aguycalled** [comment]
I'd make use of being able to set `BLS_SIG_BLS12381G2_XMD:SHA-256_SSWU_RO_NUL_` and `BLS_SIG_BLS12381G2_XMD:SHA-256_SSWU_RO_AUG_` as DST labels

**Comment by herumi** [comment]
I added hashAndMapToG1 and hashAndMapToG2 with DST for C++.
https://github.com/herumi/mcl/commit/b3f4d607cb5f823b88de11717e4f9c387606d2bb
What language do you want to use them with?

**Comment by aguycalled** [comment]
Thank you very much!

I would use it from C.

**Comment by aguycalled** [comment]
I think a function setDSTLabel(*char, size_t) which sets a global setting like setMapToMode() would be more flexible, and require less changes in other libraries like herumi/bls which use mcl for signing and verification but dont support different schemes yet.

**Comment by herumi** [comment]
I've added mclBn{G1,G2}_setDst(const char* dst, size_t dstSize) functions at https://github.com/herumi/mcl/commit/d7fe9d748ab88b342024fa2f05dc38ea773ffa00 .

**Comment by aguycalled** [comment]
👍

**Comment by b00f** [comment]
@herumi and @aguycalled Thank you so much guys for the fast implementation. I will test it soon and update you guys.

**Comment by herumi** [comment]
Is it enough only to add the global setting functions of DST?

**Comment by b00f** [comment]
That also should work. But I think become a bit far from the spec. The APIs can follow the spec, for example, we can have different Sign and Verify methods for different schema. For example look [here](https://github.com/algorand/bls_sigs_ref/blob/b499fdc44b303e681dd9f5dd8f889398da708b59/rust-impl/src/signature.rs#L48)

I think now it is very risky to touch it. Better to have a global setting.

**Comment by herumi** [comment]
I updated https://github.com/herumi/bls-go-binary to support setDst.

**Comment by b00f** [comment]
I tested it, it worked as it promised. Thanks
