### ISSUE TITLE
[Confused] About verifing mcl MCL_BN_SNARK1 curve on EVM

### ISSUE THREAD

**Issue by benbaley** [herumi/mcl#145]
Hi @herumi 
I'm a beginner in cryptography, I don't know much about the details of the algorithm, I want to do a PairingCheck verification of the MCL_BN_SNARK1 curve on EVM, I found solidity's algorithm on BLS verification in [thehubbleproject](https://github.com/thehubbleproject/hubble-contracts)'s repository, I followed the steps below:
1. generate a private key with the MCL_BN_SNARK1 curve in mcl and sign a message
2. Verify the signature and publickey through [verifySingle](https://github.com/thehubbleproject/hubble-contracts/blob/master/contracts/libs/BLS.sol#L45) in EVM(bn256Pairing), but it pairing failed
3. further checking shows that the results of [HashAndMapTo](https://github.com/herumi/mcl/blob/master/include/mcl/bn.hpp#L2064) of 2 algorithms(in mcl and [thehubbleproject](https://github.com/thehubbleproject/hubble-contracts/blob/master/contracts/libs/BLS.sol#L139)) are completely different
4. I checked that both mcl and thehubbleproject use `Fouque-Tibouchi`, the MapToMode in mcl uses `MCL_MAP_TO_MODE_ORIGINAL` by default, which looks a bit like [draft-irtf-cfrg-hash-to-curve-03](https://datatracker.ietf.org/doc/html/draft-irtf-cfrg-hash-to-curve-03), but the solidity implementation of thehubbleproject is more like [draft-irtf-cfrg-hash-to-curve-07](https://datatracker.ietf.org/doc/html/draft-irtf-cfrg-hash-to-curve-07)  or I'm not sure

Is HashAndMapTo algorithm in mcl and thehubbleproject's solidity implementation the key to the problem? How can I verify mcl.MCL_BN_SNARK1 on EVM? Can I get your help please?

**Comment by herumi** [comment]
I implemented a Fouque-Tibouchi algorithm for BN_SNARK1 before.
https://datatracker.ietf.org/doc/html/draft-irtf-cfrg-hash-to-curve-07 shows the algorithm not for MCL_BN_SNARK1 but BLS12-381.

Though I do not know thehubbleprojects, do you want the same method of mcl as it?

**Comment by benbaley** [comment]
Thank you for your reply.
Yes, I'm trying to find an algorithm that can verify the mcl.BN_SNARK1 curve signature in EVM(solidity)
Do you mean that you have implemented the Fouque-Tibouchi algorithm in solidity language before?
Looking forward to your reply :)

**Comment by herumi** [comment]
There are some variations to the algorithm:
- The way to convert a hashed value to Fr.
- The choice of a square root, etc.

So, we have to select the same them.
By the way, BLS12-381 is better than BN_SNARK1 because of security. Do you need BN_SNARK1?

**Comment by benbaley** [comment]
Thank you very much!
I will try to find the differents between them
And, I think Ethereum will support bls12-381 later, but the implementation of bls12-381 in EVM is still for testing purposes ([here](https://github.com/ethereum/go-ethereum/blob/master/core/vm/contracts.go#L96)) at this phase.

**Comment by herumi** [comment]
Do you know the implementation of EVM by C/C++/Python?
If I can see it, it is easy to check the difference between mcl and EVM.
(But I have many tasks, so I'm not sure to get the time.)

**Comment by benbaley** [comment]
I don't know much about it either, the following items look somewhat similar 😂
- [evmone](https://github.com/ethereum/evmone) is a C++ implementation of the EVM
- [Py-EVM](https://github.com/ethereum/py-evm) is an implementation of the Ethereum protocol in Python

**Comment by herumi** [comment]
I saw those links, but I could not find the algorithm of mapToPoint. Do you know the original specification document?

**Comment by benbaley** [comment]
The python version of the implementation seems to be [here](https://github.com/ethereum/py-evm/blob/master/eth/precompiles/ecpairing.py#L71), but I'm not sure
I'll go with the bls12-381 implementation, after all, ETH 2.0 will support it soon
thank you very much for your support
