### ISSUE TITLE
Go binding: maybe `SetHashOf` should compare with 0 not 1

### ISSUE THREAD

**Issue by helinwang** [herumi/mcl#15]
Thanks for the great library!

Maybe https://github.com/herumi/mcl/blob/d798881e3bcc634afd718b8a7fc62e3060dda6f5/ffi/go/mcl/mcl.go#L148-L151

Should compare with 0, not 1? E.g.,
```Go
func (x *Fr) SetHashOf(buf []byte) bool {
	// #nosec
	return C.mclBnFr_setHashOf(x.getPointer(), unsafe.Pointer(&buf[0]), C.size_t(len(buf))) == 0
}
```

Since the success value seems to be 0, and the failure value seems to be -1: https://github.com/herumi/mcl/blob/e6c316cbbd2e75a158578aed0f592141e85bf754/src/bn_c_impl.hpp#L193

**Comment by herumi** [comment]
Thank you for your verification.
I fixed [it](https://github.com/herumi/mcl/commit/5d4999f1e145fdfb0f5674b768fd68c0143c9cb9).

**Comment by helinwang** [comment]
Thank you!
Btw, same issue with "github.com/dfinity/go-dfinity-crypto/bls" if you also maintains it: https://github.com/dfinity/go-dfinity-crypto/blob/master/bls/mcl.go#L136

**Comment by helinwang** [comment]
@herumi 

Maybe rename [`err`](https://github.com/herumi/mcl/commit/5d4999f1e145fdfb0f5674b768fd68c0143c9cb9#diff-41023229a599358d03c3d651ae999ccbR29) to success:
```Go
success := x.SetHashOf([]byte("abc"))
if !success {
  t.Error(err)
}
```
