### ISSUE TITLE
Adding mapToG1 to C-API

### ISSUE THREAD

**Issue by exfinen** [herumi/mcl#151]
We have been building software based on mcl's C-API, but reazlied that mapToG1 function is only avaialble in C++-API.
Is it difficult to have it in C-API as well?
We tried to migrate to C++-API, but it was missing functions we need and didn't work either.

**Comment by herumi** [comment]
Is [mclBnFp_mapToG1](https://github.com/herumi/mcl/blob/master/include/mcl/bn.h#L335) not what you need?

**Comment by exfinen** [comment]
Sorry I have missed it and that seems to be what we need. Thank you for your quick response!
