### ISSUE TITLE
MCL uses a old version CYBOZULIB_TAG release2018050

### ISSUE THREAD

**Issue by fionser** [herumi/mcl#16]
1. current MCL uses (CYBOZULIB_TAG release2018050) which the following error pops out.
```
error: ‘uintToDec’ is not a member of ‘cybozu::itoa_local’
size_t len = cybozu::itoa_local::uintToDec(buf, bufSize - pos, r);                           
```
2. the `uintToDec` is in [this commit](https://github.com/herumi/cybozulib/commit/984f93f9268844f5a06d7aa10119647c5f3f87e8) but not in release2018050.

**Comment by herumi** [comment]
Thank you. I have updated [the tag](https://github.com/herumi/mcl/commit/626c574bf96aae2adc11d9406a2243fd67490da8).
