### ISSUE TITLE
Question: The mode in bench

### ISSUE THREAD

**Issue by XinwenXiang** [herumi/mcl#160]
I'm comparing the efficiency of mcl library and other cryptographic algorithm libraries, in bench.cpp and related file,such as op.hpp and fp.cpp. I found that there are different modes, I would like to ask what is the difference among these modes?
![image](https://user-images.githubusercontent.com/33709586/189660998-8f179422-9b64-4c5e-a0e4-47a59b9405db.png)

**Comment by herumi** [comment]
The parameters are for comparing speeds in different modes of development, and the default parameter is the fastest.
So don't worry about it.

**Comment by XinwenXiang** [comment]
Do you mean when I use mcl lib, it defaults to setting parameters for different development environments? However, when I run bench.exe, which mode should my comparison criteria be, the auto mode?
![image](https://user-images.githubusercontent.com/33709586/189823160-9c19b629-e80e-48ae-8f2f-395cb13bc1ae.png)

**Comment by herumi** [comment]
Yes. Would you please use auto-mode in any environment?

**Comment by XinwenXiang** [comment]
Ok. After completing the benchmark efficiency comparison, I will implement a cryptographic scheme based on mcl and pay attention on the modes choosed. Sincerely thanks for your answer.

**Comment by herumi** [comment]
Those modes are old (for example, GMP is not used anymore). I'm refactoring them now.
