### ISSUE TITLE
Why don't have src/asm/x86-64mac.s

### ISSUE THREAD

**Issue by ponyyuhan** [herumi/mcl#164]
Your code in CmakeLists.txt said "if(APPLE)
		target_sources(mcl PRIVATE src/asm/x86-64mac.s) --186
		target_sources(mcl_st PRIVATE src/asm/x86-64mac.s) --187
	else()
		target_sources(mcl PRIVATE src/asm/x86-64.s)
		target_sources(mcl_st PRIVATE src/asm/x86-64.s)
	endif()"

But I don't find x86-64mac.s in the file asm

**Comment by herumi** [comment]
I've removed them.
Could you try the latest CMakefile in https://github.com/herumi/mcl/blob/dev/CMakeLists.txt ?

**Comment by ponyyuhan** [comment]
Hi!

Thank you so much! It works!

Best Regards
Yuhan Ma

2022年10月5日 06:52，MITSUNARI Shigeo ***@***.******@***.***>> 写道：



I've merged it into the master branch.
