### ISSUE TITLE
build error at Mac M1 

### ISSUE THREAD

**Issue by NP-h** [herumi/mcl#165]
Hi,
leaving a post because there was an error in my process of building your library.
I'm using Mac M1, but there's error that says i can't find the library with linker command failed with exit code 1. But it works normally in my another laptop(Ubuntu) 
i want to solve the problem on my Mac M1 but i don't know even if i find a way...
Can you help me? 

 Thank you

**Comment by herumi** [comment]
Could you tell me what command you typed and what error you got?

`make test` and `make bin/pairing.exe` run well on my M1 MacBook Pro + clang 14.0.0.

**Comment by NP-h** [comment]
<img width="1438" alt="error" src="https://user-images.githubusercontent.com/118030641/201459415-5d681fa1-d200-474b-8acd-fd30a306c049.png">

Thank you for your reply
maybe this is a point... when i type make -j4 I don't know what should i do..

please let me know how can i get to the next step

Thank you

**Comment by herumi** [comment]
gmpxx is not found, then please type `brew install gmp`.

**Comment by NP-h** [comment]
I already have a gmp, so I didn't know it would be a problem, but I updated it the way you told me, so it works normally. Thank you
