### ISSUE TITLE
serialize G1 32 bytes failed for secp256k1

### ISSUE THREAD

**Issue by levyfan** [herumi/mcl#173]
Hi, I get `mclBn_getG1ByteSize=32` for secp256k1 curve, but the actual serialized length is 33. Serialize 32 bytes will fail with return size=0.

```c
#include <mcl/bn256.hpp>
#include <mcl/bn_c256.h>
#include <iostream>

int main() {
    bool pb;
    mcl::bn::initG1only(&pb, mcl::ecparam::secp256k1);
    std::cout << "init pb=" << pb << std::endl;

    mcl::bn::G1 g;
    int bytes = mclBn_getG1ByteSize();
    std::cout << "getG1ByteSize=" << bytes << std::endl;

    char buf[128];
    size_t n = g.serialize(buf, 32);
    std::cout << "serialize 32 n=" << n << std::endl;

    n = g.serialize(buf, 33);
    std::cout << "serialize 33 n=" << n << std::endl;
    return 0;
}
```

The code will output:
```
init pb=1
getG1ByteSize=32
serialize 32 n=0
serialize 33 n=33
```

What is the expected byte size of G1 for secp256k1?

**Comment by herumi** [comment]
secp256k1 is a 256-bit curve, requiring 32 bytes for x and one byte for a signed bit of y.
bn.h is mainly developed for BN254 and BLS12-381, so I don't consider other curves. I'll fix the return size later.

**Comment by levyfan** [comment]
Hi @herumi , how is it going on?

**Comment by herumi** [comment]
Could you use the magic number 33 until mclBn_getG1ByteSize() returns 33 for secp256k1?

**Comment by levyfan** [comment]
> Could you use the magic number 33 until mclBn_getG1ByteSize() returns 33 for secp256k1?

I also use go api, there would be some error when mclBn_getG1ByteSize()=32 such as here https://github.com/herumi/mcl/blob/611d1cc7eedd890ed1fc023aef18b58c238ae444/ffi/go/mcl/mcl.go#L743-L751

**Comment by herumi** [comment]
I've fixed getG1ByteSize().
https://github.com/herumi/mcl/commit/fe28741fdba01893303efa1908bd043a7ff197f6
mcl.go does not support G1only, but I modified it.

**Comment by levyfan** [comment]
@herumi another question, does `MCL_MAP_TO_MODE_HASH_TO_CURVE_07` support NIST P256 here https://www.ietf.org/archive/id/draft-irtf-cfrg-hash-to-curve-16.html#name-nist-p-256

**Comment by herumi** [comment]
The current mcl does not support it.
