### ISSUE TITLE
Getting segment fault on intel MacOS. 

### ISSUE THREAD

**Issue by RoastedGoose** [herumi/mcl#174]
Getting segment fault on intel MacOS. 
After “sudo make install” and simply called
 “initPairing()”, it caught exception “exc bad accss code exc I386 gpflt.” when running “mulUnitN()”. While the original build test works fine.

**Comment by herumi** [comment]
What is the CPU? What are the compiler options to build?

**Comment by RoastedGoose** [comment]
x86-64 intel i5 with clang++. Just follow the build method below:
For x86-64 Linux and macOS.
mkdir build
cd build
cmake ..
make
Then “sudo make install”. Create a new cpp file and include <mcl/bls12_381>, and link mcl and gmp libraries when compiling.

**Comment by herumi** [comment]
Okay, I verified the problem. It reproduces on only Intel Mac with CMake. There is no problem on the other intel Linux and intel Mac with Makefile.
I'll investigate the reason, but could you please use libmcl.a built by `make` for a while?

**Comment by RoastedGoose** [comment]
`make` works, thanks!

**Comment by xfap** [comment]
Hello, is this fixed? I got the problem again on my mac intel.

**Comment by herumi** [comment]
Please show me what kind of code you build and how you build it.

The following commands go well.

```
mkdir build
cd build
cmake .. -DMCL_BUILD_TESTING=ON -DMCL_BUILD_SAMPLE=ON
make -j
bin/bls12_test
...
```

```
clang -v
Apple clang version 15.0.0 (clang-1500.3.9.4)
Target: x86_64-apple-darwin23.4.0
uname -a
% uname -a
Darwin macpro.local 23.4.0 Darwin Kernel Version 23.4.0: Fri Mar 15 00:11:05 PDT 2024; root:xnu-10063.101.17~1/RELEASE_X86_64 x86_64
```
