### ISSUE TITLE
Checking if library has been initialized

### ISSUE THREAD

**Issue by aguycalled** [herumi/mcl#176]
Is there any way (without storing the return value of the init function for future use) to determine whether the library has been correctly initialized?

Thanks.

**Comment by herumi** [comment]
How about defining a global flag?

```cpp
std::atomic<bool> g_is_mcl_initialized;
bool is_mcl_initialized() { return g_is_mcl_initialized; }


if (initPairing(...)) {
  g_is_mcl_initialized = true;
}
```
