### ISSUE TITLE
Initialize EC curve (C++ doc is lack)

### ISSUE THREAD

**Issue by XinwenXiang** [herumi/mcl#180]
hi,

I'm trying to use secp256k1 in a C++ project , it seems that the initPairing() only support curves that support Pairing .
`mcl::bn::initPairing(mcl::BLS12_381);`
and I have read ecdsa.hpp,
it uses this to init curve:
```
inline void init(bool *pb)
{
	local::Param& p = local::getParam();
	mcl::initCurve<Ec, Zn>(pb, MCL_SECP256K1, &p.P);
	if (!*pb) return;
	p.bitSize = 256;
	p.Pbase.init(pb, p.P, p.bitSize, local::winSize);
	// isValid() checks the order
	Ec::setOrder(Zn::getOp().mp);
	Fp::setETHserialization(true);
	Zn::setETHserialization(true);
	p.serializeMode = SerializeBitcoin;
//	Ec::setIoMode(mcl::IoEcAffineSerialize);
}
```
should i use the same way to init secp256k1 in my project, and how can i get random element of G1?

**Comment by herumi** [comment]
You can use the initialization,

```cpp
#include <mcl/ecdsa.hpp>

int main()
    try
{
    using namespace mcl::ecdsa;
    init();
    Fp r;
    r.setByCSPRNG();
    Ec P;
    mcl::ec::tryAndIncMapTo(P, r);
    printf("P=%s\n", P.getStr().c_str());
} catch (std::exception& e) {
    printf("err %s\n", e.what());
    return 1;
}
```

Or

```cpp
#include <mcl/bn.hpp>

int main()
    try
{
    using namespace mcl::bn;
    bool b;
    initG1only(&b, mcl::ecparam::secp256k1);
    if (!b) {
        puts("ERR");
        return 1;
    }
    Fp r;
    r.setByCSPRNG();
    G1 P;
    mapToG1(P, r);
    printf("P=%s\n", P.getStr().c_str());
} catch (std::exception& e) {
    printf("err %s\n", e.what());
    return 1;
}
```

**Comment by XinwenXiang** [comment]
I have tried above, and I want to ask:
1. r is setByCSPRNG, it shoule be a rand number less than the Group  order of secp256k1, if tryAndIncMap() same as maptoG1()?

2. Both file print P=1, it means P is the base point of G1?
![image](https://user-images.githubusercontent.com/33709586/231637603-ed45922b-f136-4a46-bc67-09b53d53cddf.png)

**Comment by herumi** [comment]
The first `1` means that the following strings are affine coordinates.
https://github.com/herumi/mcl/blob/master/api.md#string-conversion
```
1 <x> <y> ; affine coordinate
```

**Comment by herumi** [comment]
>r is setByCSPRNG, it shoule be a rand number less than the Group order of secp256k1, if tryAndIncMap() same as maptoG1()?

The r is an element of the base field of G1, so it may be greater than the group order.
tryAndIncMap() is same as maptoG1() for secp256k1 on the current version.

**Comment by XinwenXiang** [comment]
got it!
thanks for your answer
