### ISSUE TITLE
Unable to compile cpp file in the sample folder

### ISSUE THREAD

**Issue by anujamodi0107** [herumi/mcl#188]
I am trying to compile pairing.cpp file in the sample folder, but I am getting the following compilation error (attached). I have installed MCL using the exact information available in the readme document. Can anyone please help me resolve this issue?

![error2](https://github.com/herumi/mcl/assets/27066771/ff825719-bfef-4c91-be79-95e2b8624158)
![error1](https://github.com/herumi/mcl/assets/27066771/2d6dced3-d172-4e44-b16d-49e1b0202e61)

**Comment by herumi** [comment]
Could you try

```bash
% cd mcl
% make bin/pairing.exe -j && bin/pairing.exe
```
If you still get any errors, please let me know your CPU, OS and compiler version.

**Comment by anujamodi0107** [comment]
> Could you try
> 
> ```shell
> % cd mcl
> % make bin/pairing.exe -j && bin/pairing.exe
> ```
> 
> If you still get any errors, please let me know your CPU, OS and compiler version.

Thank you for your quick response. I am still getting those errors. Here are the details of the CPU, OS, and compiler versions:
Dell Inc. OptiPlex 3050, Memory 4.0 GiB, Intel® Core™ i3-7100 CPU @ 3.90GHz × 4, 64 bit Ubuntu 22.04.3 LTS and g++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0.

**Comment by herumi** [comment]
Did you `make clean` first?
Please append the text of errors, not images.

**Comment by anujamodi0107** [comment]
> Did you `make clean` first? Please append the text of errors, not images.

Yes, I gave the command "make clean" first.
The errors in text format are in [this](https://docs.google.com/document/d/1aWAJXdeLvq8VQHHT4rWQMUIieHC58PfrC_bB2tCRFkI/edit) document.

**Comment by herumi** [comment]
Please update a log contains a line `make bin/pairing.exe`.

My env. is Ubuntu 23.0 + gcc 12.3.0.
```
mcl% make bin/pairing.exe -j
cc -c src/asm/x86-64.S -o obj/base64.o  -g3 -Wall -Wextra -Wformat=2 -Wcast-qual -Wcast-align -Wwrite-strings -Wfloat-equal -Wpointer-arith -Wundef -m64 -I include -I test -fomit-frame-pointer -DNDEBUG -fno-stack-protector -O3  -fpic -DMCL_USE_LLVM=1 -DMCL_BINT_ASM=1
cc  -g3 -Wall -Wextra -Wformat=2 -Wcast-qual -Wcast-align -Wwrite-strings -Wfloat-equal -Wpointer-arith -Wundef -m64 -I include -I test -fomit-frame-pointer -DNDEBUG -fno-stack-protector -O3  -fpic -DMCL_USE_LLVM=1 -DMCL_BINT_ASM=1 -c src/asm/bint-x64-amd64.S -o obj/bint64.o
g++  -g3 -Wall -Wextra -Wformat=2 -Wcast-qual -Wcast-align -Wwrite-strings -Wfloat-equal -Wpointer-arith -Wundef -m64 -I include -I test -fomit-frame-pointer -DNDEBUG -fno-stack-protector -O3  -fpic -DMCL_USE_LLVM=1 -DMCL_BINT_ASM=1 -c src/fp.cpp -o obj/fp.o -MMD -MP -MF obj/fp.d
g++  -g3 -Wall -Wextra -Wformat=2 -Wcast-qual -Wcast-align -Wwrite-strings -Wfloat-equal -Wpointer-arith -Wundef -m64 -I include -I test -fomit-frame-pointer -DNDEBUG -fno-stack-protector -O3  -fpic -DMCL_USE_LLVM=1 -DMCL_BINT_ASM=1 -c sample/pairing.cpp -o obj/pairing.o -MMD -MP -MF obj/pairing.d
ar rv lib/libmcl.a obj/fp.o obj/base64.o obj/bint64.o
ar: creating lib/libmcl.a
a - obj/fp.o
a - obj/base64.o
a - obj/bint64.o
g++ obj/pairing.o -o bin/pairing.exe lib/libmcl.a -lrt  -lgmp -lgmpxx -m64
```

**Comment by anujamodi0107** [comment]
> Please update a log contains a line `make bin/pairing.exe`.
> 
> My env. is Ubuntu 23.0 + gcc 12.3.0.
> 
> ```
> mcl% make bin/pairing.exe -j
> cc -c src/asm/x86-64.S -o obj/base64.o  -g3 -Wall -Wextra -Wformat=2 -Wcast-qual -Wcast-align -Wwrite-strings -Wfloat-equal -Wpointer-arith -Wundef -m64 -I include -I test -fomit-frame-pointer -DNDEBUG -fno-stack-protector -O3  -fpic -DMCL_USE_LLVM=1 -DMCL_BINT_ASM=1
> cc  -g3 -Wall -Wextra -Wformat=2 -Wcast-qual -Wcast-align -Wwrite-strings -Wfloat-equal -Wpointer-arith -Wundef -m64 -I include -I test -fomit-frame-pointer -DNDEBUG -fno-stack-protector -O3  -fpic -DMCL_USE_LLVM=1 -DMCL_BINT_ASM=1 -c src/asm/bint-x64-amd64.S -o obj/bint64.o
> g++  -g3 -Wall -Wextra -Wformat=2 -Wcast-qual -Wcast-align -Wwrite-strings -Wfloat-equal -Wpointer-arith -Wundef -m64 -I include -I test -fomit-frame-pointer -DNDEBUG -fno-stack-protector -O3  -fpic -DMCL_USE_LLVM=1 -DMCL_BINT_ASM=1 -c src/fp.cpp -o obj/fp.o -MMD -MP -MF obj/fp.d
> g++  -g3 -Wall -Wextra -Wformat=2 -Wcast-qual -Wcast-align -Wwrite-strings -Wfloat-equal -Wpointer-arith -Wundef -m64 -I include -I test -fomit-frame-pointer -DNDEBUG -fno-stack-protector -O3  -fpic -DMCL_USE_LLVM=1 -DMCL_BINT_ASM=1 -c sample/pairing.cpp -o obj/pairing.o -MMD -MP -MF obj/pairing.d
> ar rv lib/libmcl.a obj/fp.o obj/base64.o obj/bint64.o
> ar: creating lib/libmcl.a
> a - obj/fp.o
> a - obj/base64.o
> a - obj/bint64.o
> g++ obj/pairing.o -o bin/pairing.exe lib/libmcl.a -lrt  -lgmp -lgmpxx -m64
> ```

I am also getting the same as mentioned above, still not able to compile sample/pairing.cpp file

**Comment by herumi** [comment]
In my environment,
```
g++ obj/pairing.o -o bin/pairing.exe lib/libmcl.a -lrt  -lgmp -lgmpxx -m64
```
successes and `bin/pairing.exe` is made.

Does the command print the attached log in your environment, which starts the following?
```
/usr/bin/ld: /tmp/ccgoZyfS.o: warning: relocation against `mclb_mulUnit7' in read-only section `.text._ZN3mcl4bint11get_mulUnitEm[_ZN3mcl4bint11get_mulUnitEm]'
/usr/bin/ld: /tmp/ccgoZyfS.o: in function `mcl::bint::impl::Init::Init()':
pairing.cpp:(.text._ZN3mcl4bint4impl4InitC2Ev[_ZN3mcl4bint4impl4InitC5Ev]+0x11): undefined reference to `mcl::bint::initBint()'
/usr/bin/ld: /tmp/ccgoZyfS.o: in function `mcl::bint::get_add(unsigned long)':
...
```

**Comment by anujamodi0107** [comment]
> In my environment,
> 
> ```
> g++ obj/pairing.o -o bin/pairing.exe lib/libmcl.a -lrt  -lgmp -lgmpxx -m64
> ```
> 
> successes and `bin/pairing.exe` is made.
> 
> Does the command print the attached log in your environment, which starts the following?
> 
> ```
> /usr/bin/ld: /tmp/ccgoZyfS.o: warning: relocation against `mclb_mulUnit7' in read-only section `.text._ZN3mcl4bint11get_mulUnitEm[_ZN3mcl4bint11get_mulUnitEm]'
> /usr/bin/ld: /tmp/ccgoZyfS.o: in function `mcl::bint::impl::Init::Init()':
> pairing.cpp:(.text._ZN3mcl4bint4impl4InitC2Ev[_ZN3mcl4bint4impl4InitC5Ev]+0x11): undefined reference to `mcl::bint::initBint()'
> /usr/bin/ld: /tmp/ccgoZyfS.o: in function `mcl::bint::get_add(unsigned long)':
> ...
> ```

Yes, in my case also, the command succeeds. When I give the command g++ pairing.cpp, the above log is printed along with multiple linking errors.

**Comment by herumi** [comment]
>Yes, in my case also, the command succeeds. When I give the command g++ pairing.cpp, the above log is printed along with multiple linking errors.

That's not surprising if you don't link lib/libmcl.a, you'll get that kind of error.

**Comment by anujamodi0107** [comment]
I understand this. Is there any other command that can link libmcl.a?

**Comment by herumi** [comment]
What do you want?

To link libmcl.a, type either of the following commands:
```
g++ sample/pairing.cpp -I include/ lib/libmcl.a
```

```
g++ sample/pairing.cpp -I include/ -lmcl -L lib
```

**Comment by anujamodi0107** [comment]
> What do you want?
> 
> To link libmcl.a, type either of the following commands:
> 
> ```
> g++ sample/pairing.cpp -I include/ lib/libmcl.a
> ```
> 
> ```
> g++ sample/pairing.cpp -I include/ -lmcl -L lib
> ```

Great. Thank you so much for your help. I can compile and run the code. Thanx again.

**Comment by anujamodi0107** [comment]
The issue is resolved.
