### ISSUE TITLE
Generate random number of class Fr

### ISSUE THREAD

**Issue by anujamodi0107** [herumi/mcl#189]
Hello,
I want to generate a matrix of n by n whose elements need to be in class Fr. Is there a function in MCL that can do this job? I found the function mcl::fp::RandGen rg = mcl::fp::RandGen(), which generates a random number in class Fp. I want a random number in class, Fr.

Thank you in advance.

**Comment by herumi** [comment]
You can get a random number by
```cpp
Fr x;
x.setByCSPRNG();
```

See [Set a random value](https://github.com/herumi/mcl/blob/master/api.md#set-a-random-value).
