### ISSUE TITLE
Does the mcl project has replaced the ate-pairing?

### ISSUE THREAD

**Issue by huyuguang** [herumi/mcl#19]
And, now the libsnarks depends on ate-pairing, do you have port a new version libsnarks which base on mcl?

**Comment by herumi** [comment]
Yes, I want that mcl is incorporated into libsnark and have requested it [before](https://github.com/scipr-lab/libsnark/pull/63).
API has changed since then, so I'll retry pullreq again.

**Comment by herumi** [comment]
Yes. [mcl_bn256](https://github.com/herumi/libsnark/tree/mcl_bn256) is the pullreq.
But it is old, so it should be updated for the latest mcl and libsnark.

**Comment by huyuguang** [comment]
I tried your "libsnark", and tried to port it to 32bit arm Linux and x64 windows.
I found there are so many "long" in code, and as I know, the "sizeof(long)" is different between the 32bits process and 64 bits process. So should I change the "long" to int64_t?

**Comment by herumi** [comment]
Where "long" is used? mcl does not use long.

**Comment by herumi** [comment]
mcl runs on 32/64-bit architecture.
libsnark seems to use "long" but I don't know they use "long" as "int64_t".
