### ISSUE TITLE
mclBnFr_getBigEndian missing in bn.h

### ISSUE THREAD

**Issue by MisterEJ** [herumi/mcl#190]
Hi

I noticed that getBigEndian is missing from bn.h and bn.hpp while there are getLittleEndian representations.

```
mclBnFr_getBigEndian
mclBnFp_getBigEndian
```

Is there a specific reason for it not being implemented?

In addition, is there a correct way to apply a patch?

**Comment by herumi** [comment]
If you use BLS12_381, then serialize() deals with buffer as big-endian.
So you can use serialize() as getBigEndian().

```cpp
#include <mcl/bls12_381.hpp>

int main()
{
  using namespace mcl::bn;
  initPairing(mcl::BLS12_381);
  Fp x;
  x = 0x1234;
  printf("x=%s\n", x.serializeToHexStr().c_str());
  Fp::setETHserialization(true);
  printf("x=%s\n", x.serializeToHexStr().c_str());
}
```

```bash
x=341200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
x=000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001234
```

Is this feature good enough for you?
