### ISSUE TITLE
when I  'make test' on macos ,happend follow problems

### ISSUE THREAD

**Issue by coolhackboy** [herumi/mcl#20]
include/mcl/mpir.h:1789:3: error: use of undeclared identifier 'GMP_NAIL_BITS'
  __GMPN_ADD (__gmp_c, __gmp_wp, __gmp_xp, __gmp_xsize, __gmp_yp, __gmp_ysize);

![image](https://user-images.githubusercontent.com/13427145/41209171-46dc241e-6d5c-11e8-8343-8f8b332c1edf.png)

**Comment by coolhackboy** [comment]
os is 10.12.6 and GNU Make 3.81

**Comment by herumi** [comment]
I tested `make -j4 test` on macOS High Sierra 10.13.5 and it runs well.
My environments are as the followings:

Xcode Version 9.4 (9F1027a)

```
% brew list gmp
/usr/local/Cellar/gmp/6.1.2_2/include/ (2 files)
/usr/local/Cellar/gmp/6.1.2_2/lib/libgmp.10.dylib
/usr/local/Cellar/gmp/6.1.2_2/lib/libgmpxx.4.dylib
/usr/local/Cellar/gmp/6.1.2_2/lib/ (4 other files)
/usr/local/Cellar/gmp/6.1.2_2/share/info/ (3 files)
```
```
% gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.1.0 (clang-902.0.39.2)
Target: x86_64-apple-darwin17.6.0
```

If your gmp is old, then could you try `brew reinstall gmp`?
