### ISSUE TITLE
constructing a field from __int128

### ISSUE THREAD

**Issue by quwenjie** [herumi/mcl#202]
Is it possible to construct an Fr from __int128?
I see the function only supports from long long int, which is 64bits.
How can this be achieved? Is it possible?

**Comment by herumi** [comment]
If your system is a little-endian architecture such as x64, then use `setLittleEndianMod`.

```cpp
__int128 v;
Fr x;
x.setLittleEndianMod((const uint8_t*)&v, sizeof(v));
```

Remark: `v` must not be a negative integer.

**Comment by quwenjie** [comment]
Solved, thanks.
