### ISSUE TITLE
Inquiry about Fr::mulSmall

### ISSUE THREAD

**Issue by quwenjie** [herumi/mcl#205]
https://github.com/herumi/mcl/blob/882951f21c80ea09dcdab9deb75b358fdc986f76/include/mcl/fp.hpp#L122
I am really interested in why this can perform the functionality of multiplying a field element with a small integer.
I would be grateful if the author could offer some explanation on this topic.
Are there any blogs/papers recommended on this topic?
Thanks.

**Comment by herumi** [comment]
I did not refer to anything in particular. I'll write a brief explanation later. I'm sorry, but I'm busy right now, so please wait a little longer.

**Comment by herumi** [comment]
I write an algorithm of `mulUnit` and a Python script.
https://github.com/herumi/mcl/blob/master/misc/mul-approx.py
