### ISSUE TITLE
Dose it support SGX(Software Guard Extensions)?

### ISSUE THREAD

**Issue by rao2357** [herumi/mcl#209]
I want to use it inside sgx .But it is hard to included

**Comment by herumi** [comment]
Unfortunately, I don't have an SGX environment so I can't try it.

But the binary by the following command
```
make clean
make MCL_STATIC_CODE=1 -j lib/libmcl.a
```
is dedicated to BLS12-381 but probably can be used from SGX because it does not use JIT, C++ exception, or external libraries. The interface is `mcl/bn.h` in C.

**Comment by herumi** [comment]
You can't use `mclBnFr_setByCSPRNG` in SGX because it accesses `/dev/urandom`.

**Comment by rao2357** [comment]
Thank you very much, I will try again

**Comment by rao2357** [comment]
You can download the SDK for SGX and use its emulation features(don't need a real SGX environment ).Hope this helps you

> Unfortunately, I don't have an SGX environment so I can't try it.
> 
> But the binary by the following command
> 
> ```
> make clean
> make MCL_STATIC_CODE=1 -j lib/libmcl.a
> ```
> 
> is dedicated to BLS12-381 but probably can be used from SGX because it does not use JIT, C++ exception, or external libraries. The interface is `mcl/bn.h` in C.

**Comment by herumi** [comment]
I tried `ego, ' which has emulated SGX before. cf. https://github.com/herumi/bls-eth-go-binary/issues/59#issuecomment-2019853496
It ran well in my environment, but it depends on env.

**Comment by Aptx4869AC** [comment]
Although I can successfully obtain the static file using this method, it causes an error in SGX.
CXX  <=  Enclave/Enclave.cpp
/usr/bin/ld: Enclave/Enclave.o: in function `mcl::fp::Op::~Op()':
Enclave.cpp:(.text._ZN3mcl2fp2OpD2Ev[_ZN3mcl2fp2OpD5Ev]+0x10): undefined reference to `mcl::fp::Op::destroyFpGenerator(mcl::fp::FpG
/usr/bin/ld: Enclave/Enclave.o: in function `mcl::bn::local::GLV2T<mcl::FpT<mcl::bn::local::FrTag, 256ul> >::init(mcl::Vint const&,
Enclave.cpp:(.text._ZN3mcl2bn5local5GLV2TINS_3FpTINS1_5FrTagELm256EEEE4initERKNS_4VintEb[_ZN3mcl2bn5local5GLV2TINS_3FpTINS1_5FrTagEefined reference to `mclb_mulUnit7'
/usr/bin/ld: Enclave.cpp:(.text._ZN3mcl2bn5local5GLV2TINS_3FpTINS1_5FrTagELm256EEEE4initERKNS_4VintEb[_ZN3mcl2bn5local5GLV2TINS_3Fp]+0x1b2): undefined reference to `mclb_mulUnit8'
/usr/bin/ld: Enclave.cpp:(.text._ZN3mcl2bn5local5GLV2TINS_3FpTINS1_5FrTagELm256EEEE4initERKNS_4VintEb[_ZN3mcl2bn5local5GLV2TINS_3Fp]+0x1c9): undefined reference to `mclb_mulUnit9'
/usr/bin/ld: Enclave.cpp:(.text._ZN3mcl2bn5local5GLV2TINS_3FpTINS1_5FrTagELm256EEEE4initERKNS_4VintEb[_ZN3mcl2bn5local5GLV2TINS_3Fp]+0xb8f): undefined reference to `mclb_mulUnit7'
/usr/bin/ld: Enclave.cpp:(.text._ZN3mcl2bn5local5GLV2TINS_3FpTINS1_5FrTagELm256EEEE4initERKNS_4VintEb[_ZN3mcl2bn5local5GLV2TINS_3Fp]+0xb9c): undefined reference to `mclb_mulUnit8'
/usr/bin/ld: Enclave.cpp:(.text._ZN3mcl2bn5local5GLV2TINS_3FpTINS1_5FrTagELm256EEEE4initERKNS_4VintEb[_ZN3mcl2bn5local5GLV2TINS_3Fp]+0xbb3): undefined reference to `mclb_mulUnit9'
/usr/bin/ld: Enclave.cpp:(.text._ZN3mcl2bn5local5GLV2TINS_3FpTINS1_5FrTagELm256EEEE4initERKNS_4VintEb[_ZN3mcl2bn5local5GLV2TINS_3Fp]+0xee8): undefined reference to `mclb_mulUnit7'
/usr/bin/ld: Enclave.cpp:(.text._ZN3mcl2bn5local5GLV2TINS_3FpTINS1_5FrTagELm256EEEE4initERKNS_4VintEb[_ZN3mcl2bn5local5GLV2TINS_3Fp]+0xef5): undefined reference to `mclb_mulUnit8'
/usr/bin/ld: Enclave.cpp:(.text._ZN3mcl2bn5local5GLV2TINS_3FpTINS1_5FrTagELm256EEEE4initERKNS_4VintEb[_ZN3mcl2bn5local5GLV2TINS_3Fp]+0xf0c): undefined reference to `mclb_mulUnit9'
/usr/bin/ld: Enclave.cpp:(.text._ZN3mcl2bn5local5GLV2TINS_3FpTINS1_5FrTagELm256EEEE4initERKNS_4VintEb[_ZN3mcl2bn5local5GLV2TINS_3Fp]+0x1250): undefined reference to `mclb_mulUnit7'
/usr/bin/ld: Enclave.cpp:(.text._ZN3mcl2bn5local5GLV2TINS_3FpTINS1_5FrTagELm256EEEE4initERKNS_4VintEb[_ZN3mcl2bn5local5GLV2TINS_3Fp]+0x125d): undefined reference to `mclb_mulUnit8'
/usr/bin/ld: Enclave.cpp:(.text._ZN3mcl2bn5local5GLV2TINS_3FpTINS1_5FrTagELm256EEEE4initERKNS_4VintEb[_ZN3mcl2bn5local5GLV2TINS_3Fp]+0x1274): undefined reference to `mclb_mulUnit9'
/usr/bin/ld: Enclave.cpp:(.text._ZN3mcl2bn5local5GLV2TINS_3FpTINS1_5FrTagELm256EEEE4initERKNS_4VintEb[_ZN3mcl2bn5local5GLV2TINS_3Fp]+0x15a8): undefined reference to `mclb_mulUnit7'
/usr/bin/ld: Enclave.cpp:(.text._ZN3mcl2bn5local5GLV2TINS_3FpTINS1_5FrTagELm256EEEE4initERKNS_4VintEb[_ZN3mcl2bn5local5GLV2TINS_3Fp]+0x15b5): undefined reference to `mclb_mulUnit8'
/usr/bin/ld: Enclave.cpp:(.text._ZN3mcl2bn5local5GLV2TINS_3FpTINS1_5FrTagELm256EEEE4initERKNS_4VintEb[_ZN3mcl2bn5local5GLV2TINS_3Fp]+0x15cc): undefined reference to `mclb_mulUnit9'
/usr/bin/ld: Enclave/Enclave.o: in function `mcl::bn::local::MapTo::initBLS12(mcl::Vint const&, int)':
Enclave.cpp:(.text._ZN3mcl2bn5local5MapTo9initBLS12ERKNS_4VintEi[_ZN3mcl2bn5local5MapTo9initBLS12ERKNS_4VintEi]+0xbda): undefined r
/usr/bin/ld: Enclave.cpp:(.text._ZN3mcl2bn5local5MapTo9initBLS12ERKNS_4VintEi[_ZN3mcl2bn5local5MapTo9initBLS12ERKNS_4VintEi]+0xbeb)/usr/bin/ld: Enclave.cpp:(.text._ZN3mcl2bn5local5MapTo9initBLS12ERKNS_4VintEi[_ZN3mcl2bn5local5MapTo9initBLS12ERKNS_4VintEi]+0xc06)/usr/bin/ld: Enclave/Enclave.o: in function `mcl::bn::local::Param::init(bool*, mcl::CurveParam const&, mcl::fp::Mode)':
Enclave.cpp:(.text._ZN3mcl2bn5local5Param4initEPbRKNS_10CurveParamENS_2fp4ModeE[_ZN3mcl2bn5local5Param4initEPbRKNS_10CurveParamENS_to `mclb_mulUnit7'
/usr/bin/ld: Enclave.cpp:(.text._ZN3mcl2bn5local5Param4initEPbRKNS_10CurveParamENS_2fp4ModeE[_ZN3mcl2bn5local5Param4initEPbRKNS_10Ced reference to `mclb_mulUnit8'
/usr/bin/ld: Enclave.cpp:(.text._ZN3mcl2bn5local5Param4initEPbRKNS_10CurveParamENS_2fp4ModeE[_ZN3mcl2bn5local5Param4initEPbRKNS_10Ced reference to `mclb_mulUnit9'
collect2: error: ld returned 1 exit status
make[1]: *** [sgx_t.mk:145: Enclave.so] Error 1
make[1]: Leaving directory '/root/sgx/mcl_bls_test/Server'
make: *** [Makefile:6: all] Error 2

> Unfortunately, I don't have an SGX environment so I can't try it.
> 
> But the binary by the following command
> 
> ```
> make clean
> make MCL_STATIC_CODE=1 -j lib/libmcl.a
> ```
> 
> is dedicated to BLS12-381 but probably can be used from SGX because it does not use JIT, C++ exception, or external libraries. The interface is `mcl/bn.h` in C.

**Comment by herumi** [comment]
Please append compiler options `-DMCL_MAX_BIT_SIZE=384 -DMCL_STATIC_CODE` with `lib/libmcl.a`.
