### ISSUE TITLE
run bin/ecdsa_c_test.exe error

### ISSUE THREAD

**Issue by HuangMinming** [herumi/mcl#214]
Hi everyone,
    I tried to run bin/ecdsa_c_test.exe in ubuntu 20.04, but it failed. The output is showed below. How to solve it, Thanks.

```sh
$ ./bin/ecdsa_c_test.exe
ctest:module=ecdsa
ok1ctest:  ecdsa is stopped by exception randomgenerator
ctest:name=ecdsa_c_test, module=1, total=2, ok=1, ng=0, exception=1
```

**Comment by herumi** [comment]
`bin/ecdsa_c_test.exe` runs well with the default mcl setting.
```
make clean
make bin/ecdsa_c_test.exe && bin/ecdsa_c_test.exe
```
`MCL_STATIC_CODE=1` is an experimental mode to use BLS12-381 pairing with minimum C++ functions.
So, you can just use it at your own risk.

**Comment by HuangMinming** [comment]
Thanks, the problem was solved.
