### ISSUE TITLE
cross compilation from Linux to Windows

### ISSUE THREAD

**Issue by ndesmoul** [herumi/mcl#218]
Is it possible to cross compile the library from Linux to Windows?

I think I managed to do it with older version of MCL (1.60), using mingw package and by defining: 

export CC=x86_64-w64-mingw32-gcc
export CXX=x86_64-w64-mingw32-g++

Some other options were also necessary in C and CXX FLAGS.

Since then the library evolved and I doesn't work anymore. In particular because of base64.ll and base32.ll files that need LLVM I think.

Is there a way to do it? Note that in my case I don't need an optimized version of the library. Just something working for development purpose.

**Comment by herumi** [comment]
`libbls384_256.a` in https://github.com/herumi/bls contains all functions of mcl.

Build `libbls384_256.a` and `mcl/sample/pairing.cpp` for mingw64.
```
git clone --recursive https://github.com/herumi/bls
cd bls
make -f Makefile.onelib CXX=x86_64-w64-mingw32-g++ MCL_USE_LLVM=0 OS=mingw64 LIB_DIR=./
x86_64-w64-mingw32-g++ -o pairing.exe -I mcl/include/ mcl/sample/pairing.cpp -DMCL_MAX_BIT_SIZE=384 libbls384_256.a
```
`pairing.exe` runs on mingw64.

**Comment by ndesmoul** [comment]
Ok, I find a little strange to have to use a sub-project, but never mind.

I have tested your solution, and indeed I can then link my own code to the libbls384_256.a file. My test executable compiles and run well using wine (I don't have a Windows at hand at the moment).

Maybe you could add this cross compilation procedure into the projet README.

Thanks for your answer.
