### ISSUE TITLE
Question about BN-381-1 and BN-381-2

### ISSUE THREAD

**Issue by NickyYangYang** [herumi/mcl#23]
Hi，
    You support two 381 bits BN curve : N-381-1 and BN-381-2.  The first one is a  A Family of Implementation-Friendly BN Elliptic Curves, the second one is used in relic-toolkit. Then , are they both security?  And , is there other difference except their params.  And which one is more faster?

**Comment by herumi** [comment]
The security level of these parameter is almost same. BN381-1 is a little(5%) faster than BN381-2.
