### ISSUE TITLE
why not implement EcT operator*()?

### ISSUE THREAD

**Issue by huyuguang** [herumi/mcl#32]
I found Fp has `operator+-*/,` and EcT has` operator+-`, but does not have `operator*`, why?
Does here have any essential reasons?

**Comment by herumi** [comment]
I do not make EcT::operator* because the types of arguments of EcT::mul is not same.

**Comment by huyuguang** [comment]
The `operator*` does not need the same types of arguments, so I can add some global operator functions by myself?

**Comment by herumi** [comment]
>The operator* does not need the same types of arguments

Of course, I know it, but Ec::mul overloads three kinds of integer type and I wait to decide whether to implement both E * INT and INT * E.

**Comment by herumi** [comment]
I added E * INT and E*= INT.
https://github.com/herumi/mcl/commit/bb4735dddc22458abacc4ac9714df79e3aff13ba

**Comment by herumi** [comment]
>Why not just use the same code in EcT?

`Operator` is for a field class and requires add, sub, mul and div so it can not be applied to EcT, which is an addtive group class.

**Comment by huyuguang** [comment]
> I added E * INT and E*= INT.
> [bb4735d](https://github.com/herumi/mcl/commit/bb4735dddc22458abacc4ac9714df79e3aff13ba)

Also add `E * Fr` and `E *= Fr`, please.

**Comment by herumi** [comment]
>Also add E * Fr and E *= Fr, please.

https://github.com/herumi/mcl/commit/bb4735dddc22458abacc4ac9714df79e3aff13ba has already supported it.

**Comment by huyuguang** [comment]
> > Also add E * Fr and E *= Fr, please.
> 
> [bb4735d](https://github.com/herumi/mcl/commit/bb4735dddc22458abacc4ac9714df79e3aff13ba) has already supported it.

The INT is a template type name, very thanks!
