### ISSUE TITLE
Order of G2 group

### ISSUE THREAD

**Issue by StefanosChaliasos** [herumi/mcl#35]
How can I get the order of G2 group of CurveSNARK1?

**Comment by StefanosChaliasos** [comment]
I want to get the value declared [here](https://github.com/scipr-lab/libff/blob/04094606d6e90f4d6a2d6a9d32a3a5a660b67bd4/libff/algebra/curves/bn128/bn128_init.cpp#L38) in libff as an Fr element.

**Comment by herumi** [comment]
How about this?
```
#include <mcl/bn256.hpp>
#include <iostream>

int main()
{
    mcl::bn::initPairing(mcl::BN_SNARK1);
    std::cout << "r=" << mcl::bn::BN::param.r << std::endl;
}

r = 21888242871839275222246405745257275088548364400416034343698204186575808495617
```

**Comment by StefanosChaliasos** [comment]
Thanks a lot @herumi !
