### ISSUE TITLE
Questions regarding backend implementation

### ISSUE THREAD

**Issue by trustyrust** [herumi/mcl#36]
Hi @herumi 

I am interested in contributing to the repo to attempt to provide faster signature verification. For this, I wanted to understand the underlying implementation of the miller_loop and finalexp functions. As far as I understand, these functions are implemented in the llvm IR. I am having some trouble understanding what is going on. Do you have more high-level code on the miller_loop and finalexp implementation?

Kind regards

**Comment by herumi** [comment]
The pairing is written in C++ ; mcl/bn.hpp
* https://eprint.iacr.org/2010/354
* https://eprint.iacr.org/2010/526
* https://eprint.iacr.org/2014/401

But some detail is a little different. Maybe, there is no complete documents about it.

bn.hpp requires some elementary arithmetic operations such as Fp::add, mul, etc.
These functions are written in
* mpn functions of GMP ; src/low_func.hpp
    * or use mcl/vint.hpp (standard C++) for WebAssembly
* src/asm/x86-64.s etc. compiled base64.ll generated by src/gen.cpp
* src/fp_generator.hpp for more optimization for x64

**Comment by herumi** [comment]
> I have written Rust wrappers for mcl and bls. Would you like me to push a pull request for these?

Thank you. Does it use bn.h and is put in ffi/rust/*? I'll see your code.

**Comment by trustyrust** [comment]
Yes, I used bindgen using bn.h and then I wrapped the generated code in some nice functions that accept references for the mclBn.. types. I measured performance in Rust and it's the same as in C++

**Comment by trustyrust** [comment]
Also, a few more questions:

1. Do you think we could benefit from making use of AVX2 intrinsics for computing the miller loop and finalexp?
2. Does this group make use of Montgomery ladder or wNAF tricks to speed up public key generation?
3. If one component of the pairing is fixed, e.g. in the context of verifying a BLS signature, do you believe it would make sense to optimize further than precomputing the G2 coefficients (https://eprint.iacr.org/2010/342.pdf)?

**Comment by herumi** [comment]
>Do you think we could benefit from making use of AVX2 intrinsics for computing the miller loop and finalexp?

I tried to use AVX before but it was slower than the current code.
I'll try again for a new CPU later.

>Does this group make use of Montgomery ladder or wNAF tricks to speed up public key generation?

G2::mul() uses GLV method.

>do you believe it would make sense to optimize further than precomputing the G2 coefficients?

I do not know.
