### ISSUE TITLE
Getting the base point in golang

### ISSUE THREAD

**Issue by kc1212** [herumi/mcl#38]
Hi, I need to generate points deterministically in order to make comparisons with alternative implementations. 

What I have so far is the following:
```
	var f Fr
	f.SetInt64(x)

	var g1, gout G1
	// TODO set g1 to the base point
	G1Mul(&gout, &g1, &f)
```
but obviously `gout` is zero because `g1` is zero.

How can I set `g1` to the base point? I didn't see an API to do it.

**Comment by herumi** [comment]
Please use `mcl::bn::hashAndMapToG1`(C++) or `mclBnG1_hashAndMapTo`(C). cf. https://github.com/herumi/mcl#map-to-points
