### ISSUE TITLE
how to accelerate g*f by precompute?

### ISSUE THREAD

**Issue by huyuguang** [herumi/mcl#42]
The speed of `g*f `(BN curve) in `mcl `is very fast, much faster than normal `wNAF` algorithm.

In my scenario, the `g` is hardcoded, so I think I can accelerate the speed of `g*f `by precompute and cache some data, for example, `2g, 4g, 8g,16g ...` , then I can convert the` g*f `to `test_bit&add`. But to my surprise, I found the `test_bit&add` version only slightly faster (20%~30%) than `mcl `version. 

So, what should I do? How can I accelerate the speed for 100% or more by precompute/cache? Could you please give some suggestions (or some URLs)?

**Comment by herumi** [comment]
Use `mcl/window_method.hpp` as the followings:

```
#include <mcl/window_method.hpp>
mcl::fp::WindowMethod<G1> wm;
wm.init(P, Fr::getBitSize(), 4 /* winSize */); // precompute a table for a fixed P with 4-bit window size
Fr x;
wm.mul(P1, x); // instead of G1::mul(P1, P, x);
```
If increasing winSize then it requires more memory and computes more faster.

**Comment by huyuguang** [comment]
Very thanks, I will try it.

**Comment by huyuguang** [comment]
It works fine. I use `init(g, bit_size, 8)` and got 500% speed. Thanks again.
