### ISSUE TITLE
Link fp.o in libmclbn512 (probably others)

### ISSUE THREAD

**Issue by wemeetagain** [herumi/mcl#44]
I ran `make`, copied the lib files to my /usr/local/lib/
I tried to import the built libmclbn512, got an error 
`Error opening shared object "libmclbn512.so":
  /usr/local/lib/libmclbn512.so: undefined symbol: _ZN3mcl2fp2Op18destroyFpGeneratorEPNS0_11FpGeneratorE`

Edited `Makefile` to include `$(LIB_OBJ)` next to `$(BN512_OBJ)` on L169.
Recompiled, imported with no error.

**Comment by herumi** [comment]
Could you use a link option "-lmclbn512 -lmcl" ?

**Comment by wemeetagain** [comment]
:+1: thanks for the tip. sorry for the bother, I'm still new at these things.
