### ISSUE TITLE
plan to release new versions?

### ISSUE THREAD

**Issue by openluopworld** [herumi/mcl#49]
Hi herumi, release20170402 can not be compiled without GMP. Do you have plan to release new versions? Thanks.

**Comment by herumi** [comment]
I do not make a release tag.
Could you use the latest version of the master branch of mcl if [building status](https://travis-ci.org/herumi/mcl) is passing?

**Comment by openluopworld** [comment]
The latest code works well. Since it's more formal to use release version than master branch daily commit, so I make this issue. Thanks.

**Comment by herumi** [comment]
Ok, I see.

**Comment by openluopworld** [comment]
Thanks sincerely.
