### ISSUE TITLE
how encrypt an "byte series"

### ISSUE THREAD

**Issue by mccoysc** [herumi/mcl#52]
as the title:
i have a byte array:
char a[64]={};
how can i encrypt a to EncG1 or EncG2?
i need encryt every byte using many encryption loops?

**Comment by mccoysc** [comment]
in example ,i just found that encG1 to encrypt a integer number.
no any example for encrypt a memory buffer.

**Comment by mccoysc** [comment]
@herumi

**Comment by herumi** [comment]
she.hpp is homomorphic encryption, so encG1 supports only integer.

**Comment by mccoysc** [comment]
can add bigNumber support?
then memory buffer can transfer to bignumber and can run as "integer"

**Comment by mccoysc** [comment]
@herumi

**Comment by mccoysc** [comment]
like this bignumber library:
https://github.com/Limeoats/BigNumber

**Comment by mccoysc** [comment]
and this one
https://github.com/kokke/tiny-bignum-c

**Comment by herumi** [comment]
>can add bigNumber support?

No. my homomorphic encryption supports one multiplication of ciphertexts for integers, so it is difficult to deal with generic big integers.
