### ISSUE TITLE
Want to use static library in a golang project.

### ISSUE THREAD

**Issue by xcshuan** [herumi/mcl#54]
I want to use the library in a golang project use cgo, first, I use **"sudo make install"** and the libraries install in **"/usr/local"**, but "/usr/local/lib" has only "libmcl.a" and "libmcl.so", and I move "libmclbn384.a" and "libmclbn384.so" from "mcl/lib" to "/usr/local/lib" and the go code works well.

![1752504875](https://user-images.githubusercontent.com/24284441/57197015-c73cbc00-6f94-11e9-8f2e-bf609a9457a5.jpg)

but if I want to use **pure static library**(copy the *.a and *.h to golang project),  How should I do? I think I should change all the header file about path, and specify the link path where the static library locate. I try to do that, but don't work. Is there some idea to do that? I'm not familiar with C++.
```
/*
#cgo  CFLAGS:-DMCLBN_FP_UNIT_SIZE=6
#cgo LDFLAGS:-L ./lib -lmclbn384 -lmcl
#include "./include/bn.h"
*/
import "C"
import "fmt"
import "unsafe"
```

**Comment by herumi** [comment]
If there are a shared library and a static library having the same name in the same directory, then the shared library is linked.
So one way to link static library is as the followings:

1. copy only libmcl.a and libmclbn384_256.a in /usr/local/lib (don't copy shared library)
2. `env CGO_LDFLAGS="-lmclbn384_256 -lmcl -lstdc++ -lgmp -lgmpxx -lcrypto" go build -tags bn384_256 aaa.go`

```
cat aaa.go
package main
import (
    "fmt"
    "github.com/herumi/mcl/ffi/go/mcl"
)

func main() {
    mcl.Init(mcl.BLS12_381)
    var a mcl.Fr
    a.SetString("256", 10)
    fmt.Printf("a=%s\n", a.GetString(16))
}
```

**Comment by xcshuan** [comment]
@herumi Thanks.... I have tested your library in our project, it works well.
