### ISSUE TITLE
What is the curve parameter of BN462?

### ISSUE THREAD

**Issue by no2233t** [herumi/mcl#56]
Can you please give the curve parameter of BN462 in decimal form, please? Thanks a lot.

**Comment by no2233t** [comment]
I'm sorry about issue #55, obviously I made a mistake and sent it before describing it.

**Comment by herumi** [comment]
I wrote it at https://github.com/herumi/mcl/#curve-parameter .

**Comment by no2233t** [comment]
Thanks!
