### ISSUE TITLE
Use cmake for the build system

### ISSUE THREAD

**Issue by arybczak** [herumi/mcl#6]
Current situation with hand-written makefiles is less than ideal, because:

1. There is no `make install`.
2. A lot of things are hardcoded (e.g. -O* always overrides compilation flags you can set from the command line, you can't compile with -flto because `ar` command is hardcoded, linking of 32bit libmcl_dy.so on 64bit system fails because no -m32 is passed to linker)
3. Windows and Linux need separate makefiles.

**Comment by herumi** [comment]
If I add CmakeLists.txt, then is it ok?

**Comment by arybczak** [comment]
Yes, that would also work :)

**Comment by herumi** [comment]
I added a [CMakeList.txt](https://github.com/herumi/mcl/blob/master/CMakeLists.txt) though it is not checked on Windows.
It is my first CMakeList.txt then I think there are some problems.

**Comment by arybczak** [comment]
Works great, thanks!
