### ISSUE TITLE
performance of bls12-381

### ISSUE THREAD

**Issue by huyuguang** [herumi/mcl#65]
I just tested the bls12-381.
To my surprise, the bls12-381 is much slower than bn254. 
I tested 1000 times ecc_mul, bn254 use 90ms, and bls12-381 use 900ms.
Why? Maybe I made some mistakes(some optimize compile flags)?

**Comment by huyuguang** [comment]
sorry, I made a mistake. Should be 90 vs 380.

**Comment by herumi** [comment]
What CPU did you use? The rate of bls12-381 to bn254 is about less than 3.
[benchmark](https://github.com/herumi/mcl#benchmark)
