### ISSUE TITLE
Are MapToG1 and MapToG2 invertable?

### ISSUE THREAD

**Issue by Zhiyi-Zhang** [herumi/mcl#74]
Functions MapToG1 and MapToG2 can map Fr into G1 and G2.
Are there any APIs to recovery the Fr from a G1 or a G2?

**Comment by herumi** [comment]
No, there is no recovery function.

**Comment by Zhiyi-Zhang** [comment]
Thank you for your reply. Is this limited by the underlying cryptographic construction? or is it not yet implemented?

**Comment by herumi** [comment]
MapToGi is not one-to-one function, so there is no inverse map.
