### ISSUE TITLE
Pairing on Fp254BNb returns 0 if element from G2 is zero

### ISSUE THREAD

**Issue by arybczak** [herumi/mcl#8]
Likely a minor issue, but pairing on Fp254BNb (I didn't check other curves) returns 0 whenever it is passed an element from G2 that is zero (if element from G1 is zero, it correctly returns 1).

**Comment by herumi** [comment]
Thank you for pointing it out.
I fixed it. https://github.com/herumi/mcl/commit/e7bf6b32447dba7d9789b8d726f02b86ab459065

**Comment by arybczak** [comment]
Thanks!
