### ISSUE TITLE
DST in msgToG1

### ISSUE THREAD

**Issue by lgremy** [herumi/mcl#85]
Hi,
in the function `void msgToG1(G1& out, const void *msg, size_t msgSize) const` of `include/mcl/mapto_wb19.hpp`, I suppose that the DST should be `BLS_SIG_BLS12381G1_XMD:SHA-256_SSWU_RO_POP_` instead of `BLS_SIG_BLS12381G2_XMD:SHA-256_SSWU_RO_POP_`.

I may do a PR to solve this issue if I did not do a mistake.

**Comment by lgremy** [comment]
Sorry, by rereading the DST, I suppose that the DST is the same in both `msgToG1` and `msgToG2` to match the minimal-pubkey-size requirements of [BLS Signatures](https://tools.ietf.org/html/draft-irtf-cfrg-bls-signature-04).

Then, I suppose this issue may be closed.

**Comment by herumi** [comment]
Thank you for the useful feedback.
Is it okay ? https://github.com/herumi/mcl/commit/0d9af2d2032960919fc6e656262e3a318922b249

**Comment by lgremy** [comment]
Yes, thanks!
