### ISSUE TITLE
How to Use MCL on Android?

### ISSUE THREAD

**Issue by Henzi96** [herumi/mcl#89]
Hello, i would like to use MCL library on Android. I am using Android NDK to call Native C/C++ code into my App. Please can you add some Information about the correct way? Or link to a tutorial ? I was looking everywhere. Thanks

**Comment by herumi** [comment]
I'm sorry that I do not provide a tutorial on Android now. 

There are some ways.

1. https://github.com/herumi/bls-eth-go-binary/ provides a static library for Android, which contains mcl functions. You can use them through [gomobile](https://github.com/golang/go/wiki/Mobile) . 

2. https://github.com/herumi/mcl/tree/master/ffi/java provides JNI of mcl. If you can build libmcljava.so for Android by cross-compile, then you can use mcl such as https://github.com/herumi/mcl/blob/master/ffi/java/MclTest.java .

**Comment by Henzi96** [comment]
Hello, thank you for your reply. I decided to choose option n.2. I am still
stuck. I dont know how to create a ".so" file from link you have send me. I
am a University student working on my final thesis. What about short call?
I know that your time is not cheap, so i can pay you lets say 20 Dollars ?
I really just need to use MCL library in my Android project ! Please help !
I have skype, Microsoft Teams or via Facebook call.

Dont let me die man !


po 16. 11. 2020 v 12:33 odesílatel MITSUNARI Shigeo <
notifications@github.com> napsal:

**Comment by herumi** [comment]
I think that an Android developer can make a shared library `libmcljava.so` relatively easily by referring X and Y,  though I've not tested it yet.
- https://github.com/herumi/bls-eth-go-binary/tree/master/android/jni
- https://github.com/herumi/mcl/blob/master/ffi/java/Makefile#L36
- `libbls384_256.a` can be used instead of `libmcl.a`

If I had time, then I'll try it, but I have many tasks now. So I'm sorry that I don't know when I can do it.

**Comment by herumi** [comment]
I'm making a sample of mcl on Android. https://github.com/herumi/mcl-android

Though there are some [restrictions](https://github.com/herumi/mcl-android#restriction) yet, I can call C++ interface.

https://github.com/herumi/mcl-android/blob/main/app/src/main/cpp/hello-libs.cpp#L39-L45


If you can solve those restrictions, could you tell me the way?
I think that it is not difficult to call JNI.

**Comment by Henzi96** [comment]
Its is not good for me. I need to make .so file from
mcl/ffi/java/mcl_wrap.cxx for android version. Maybe ndk_build is good for
me.

po 23. 11. 2020 v 12:35 odesílatel MITSUNARI Shigeo <
notifications@github.com> napsal:

**Comment by Henzi96** [comment]
I need to make so file from mcl/ffi/java/mcl_wrap.cxx for android version
with ndk-build Can you help me with this way?

po 23. 11. 2020 v 15:46 odesílatel Jan Strakoš <jan.strakos.honza@gmail.com>
napsal:

**Comment by herumi** [comment]
This project already contains [mcl_wrap.cxx](https://github.com/herumi/mcl-android/blob/main/app/src/main/cpp/CMakeLists.txt#L10). So I think that you can use JNI only if you set the path to `com.herumi.mcl` (but now I can not find it now on Android Studio).

**Comment by Henzi96** [comment]
this is my make file:
Where is the problem ?

po 23. 11. 2020 v 20:28 odesílatel MITSUNARI Shigeo <
notifications@github.com> napsal:

**Comment by Henzi96** [comment]
https://github.com/herumi/mcl-android/blob/main/app/src/main/cpp/CMakeLists.txt#L10
<https://www.codementor.io/redirect-notice?url=https%3A%2F%2Fgithub.com%2Fherumi%2Fmcl-android%2Fblob%2Fmain%2Fapp%2Fsrc%2Fmain%2Fcpp%2FCMakeLists.txt%23L10>
This is compile error because there are no files

po 23. 11. 2020 v 20:35 odesílatel Jan Strakoš <jan.strakos.honza@gmail.com>
napsal:

**Comment by herumi** [comment]
I've added Android.mk and Application.mk at https://github.com/herumi/mcl/tree/master/ffi/java/android/jni . It generates libmcljava.so.

**Comment by Henzi96** [comment]
Works, thanks
