### ISSUE TITLE
mclBnGT_mul is valid or not

### ISSUE THREAD

**Issue by dandelionzbx** [herumi/mcl#90]
GT is multiplicative subgroup of F_p^12, the following API for C
"void mclBnGT_mul(mclBnGT *z, const mclBnGT *x, const mclBnGT *y)"
I think x and y should be elements in GT, however, the specific implementation does not determine that the element belongs to GT, they are in F_p^12. Whether this is valid？

**Comment by herumi** [comment]
mclBnGT_mul computes z = x * y for x, y in Fp^12, and if x and y in GT, then the computed value z belongs to GT.
