### ISSUE TITLE
How to map  "char*" to “GT” and how to inverse？

### ISSUE THREAD

**Issue by szcnnn** [herumi/mcl#91]

**Comment by herumi** [comment]
"cha*" means serialization, then use `mclBnGT_serialize` and `mclBnGT_deserialize`.
If it means a string, then use `mclBnFp_getStr` and `mclBnFp_setStr` for each member `d[0]`, ..., d[11]`.

**Comment by szcnnn** [comment]
Is the outputs of ` mclBnGT_getStr`    a point on   GT?

**Comment by herumi** [comment]
GT has 12 elements of Fp (Fp d[12]), so it outputs `d[0] d[1] d[2] ... d[11]`.
